title: "Linear Algebra, Geometry, and Computation"
author: "Mark Crovella"
logo: images/DiagramAR-icon.png
repository:
        url: https://github.com/mcrovella/CS132-Geometric-Algorithms
html:
        favicon: images/DiagramAR-icon.png
        use_repository_button: true
execute:
  execute_notebooks: "off"
